from __future__ import annotations

import base64
import json
import os
from typing import Any

import requests


def env_flag(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def build_slack_message(response: dict[str, Any], report_url: str) -> dict[str, Any]:
    evidence = response.get("anomaly_evidence", [])
    top_evidence = evidence[0]["reason"] if evidence else response.get("suspected_root_cause", {}).get("evidence", [""])[0]
    actions = response.get("recommended_actions", [])
    top_action = actions[0].get("summary") if actions else "Review incident context."
    return {
        "text": (
            f"{response.get('severity', 'unknown').upper()} {response.get('classification')} "
            f"for {response.get('incident_id')} ({response.get('status')}, confidence {response.get('confidence', 0):.2f}). "
            f"Top evidence: {top_evidence} Action: {top_action} Report: {report_url}"
        )
    }


def publish_slack_webhook(
    response: dict[str, Any],
    report_url: str,
    dry_run: bool = False,
    http_post: Any | None = None,
) -> dict[str, Any]:
    webhook = os.getenv("SLACK_WEBHOOK_URL")
    payload = build_slack_message(response, report_url)
    if dry_run or not webhook:
        result = {
            "provider": "slack",
            "status": "dry_run",
            "reason": "dry_run_enabled" if dry_run else "missing_SLACK_WEBHOOK_URL",
            "payload": payload,
        }
        print(json.dumps({"slack_dry_run": payload, "reason": result["reason"]}, indent=2))
        return result

    post = http_post or requests.post
    slack_response = post(webhook, json=payload, timeout=5)
    slack_response.raise_for_status()
    result = {"provider": "slack", "status": "published", "incident_id": response.get("incident_id")}
    print(json.dumps({"slack_published": True, "incident_id": response.get("incident_id")}, indent=2))
    return result


def build_jira_issue_payload(response: dict[str, Any]) -> dict[str, Any]:
    ticket = response.get("ticket_payload") or {}
    fields = ticket.get("fields") or {}
    labels = [str(label).replace(" ", "-")[:255] for label in ticket.get("labels", []) if label]
    issue_fields: dict[str, Any] = {
        "project": {"key": ticket.get("project") or os.getenv("JIRA_PROJECT_KEY", "OPS")},
        "summary": ticket.get("summary") or f"{response.get('incident_id', 'incident')} needs triage",
        "description": {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": ticket.get("description") or "Generated by TF1 AI triage."}],
                },
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": f"Audit ID: {fields.get('audit_id') or response.get('audit_id')}"}],
                },
            ],
        },
        "issuetype": {"name": os.getenv("JIRA_ISSUE_TYPE", "Task")},
        "labels": labels,
    }
    assignee = fields.get("suggested_assignee_account_id") or response.get("suggested_assignee_account_id")
    if assignee:
        issue_fields["assignee"] = {"accountId": assignee}
    return {"fields": issue_fields}


def create_jira_issue(
    response: dict[str, Any],
    dry_run: bool = False,
    http_post: Any | None = None,
) -> dict[str, Any]:
    base_url = (os.getenv("JIRA_BASE_URL") or "").rstrip("/")
    email = os.getenv("JIRA_EMAIL")
    api_token = os.getenv("JIRA_API_TOKEN")
    payload = build_jira_issue_payload(response)
    missing = [name for name, value in {"JIRA_BASE_URL": base_url, "JIRA_EMAIL": email, "JIRA_API_TOKEN": api_token}.items() if not value]
    if dry_run or missing:
        result = {
            "provider": "jira",
            "status": "dry_run",
            "reason": "dry_run_enabled" if dry_run else f"missing_{','.join(missing)}",
            "payload": payload,
        }
        print(json.dumps({"jira_dry_run": payload, "reason": result["reason"]}, indent=2))
        return result

    token = base64.b64encode(f"{email}:{api_token}".encode("utf-8")).decode("ascii")
    headers = {
        "Authorization": f"Basic {token}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
    post = http_post or requests.post
    jira_response = post(f"{base_url}/rest/api/3/issue", json=payload, headers=headers, timeout=10)
    jira_response.raise_for_status()
    body = jira_response.json()
    result = {
        "provider": "jira",
        "status": "created",
        "issue_key": body.get("key"),
        "issue_id": body.get("id"),
        "incident_id": response.get("incident_id"),
    }
    print(json.dumps({"jira_issue_created": result}, indent=2))
    return result
